### ISSUE TITLE
[docs] Switch between versions

### ISSUE THREAD

**Issue by richgilbank** [Shopify/js-buy-sdk#122]
Currently the docs are independent of the lib version - we should be able to switch between versions and display the docs from each one.

**Comment by tessalt** [comment]
hm that's probably going to be a significant update to the hacky way we're doing docs. @m-ux have you done any more investigation into documentation solutions?

**Comment by m-ux** [comment]
only really know about jsdoc at the moment, but jsdoc generates to a subfolder based on the version number specified in your package.json

When you rev the version number & regenerate the docs, it will go in a new folder.  

One thing you can do (lodash docs used to do this, but are slightly different now) is have a dropdown to select version numbers that link to the appropriate code.  

There's also the `version`, `since` and `deprecated` properties, which could theoretically be used to more dynamically showcase stuff... but that could be a lot more complicated.

We've got a simple implementation of jsdoc outputting to raw json data which we'd like to use at some point in the future for a more robust solution - you'd likely need to approach the problem that way to take advantage of the version/since/deprecated properties.

**Comment by lopugit** [comment]
do it, I'll help

**Comment by mikkoh** [comment]
You can now generate docs for specific versions. It's documented here:
https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md#documentation
