### ISSUE TITLE
config - myShopifyDomain is deprecated

### ISSUE THREAD

**Issue by lopugit** [Shopify/js-buy-sdk#157]
when I import the sdk via 

`<script src="http://sdks.shopifycdn.com/js-buy-sdk/latest/shopify-buy.polyfilled.globals.min.js"></script>`

and then run 

```
$(function() {	
	var shopClient = ShopifyBuy.buildClient({
    apiKey: 'c261639496a0e00d4d9a2cd445eb7a5a',
    myShopifyDomain: 'my-leisure',
    appId: '6'
  });
```

it spits out the error 

`[JS-BUY-SDK]:  Config -  myShopifyDomain is deprecated, please use domain and provide the full shop domain.`

**Comment by richgilbank** [comment]
Hi @lopugit,
Please see my response to your stack overflow question, which covers this as well:
http://stackoverflow.com/questions/38262625/shopify-buy-sdk-getelementbyid-onclick-functions-not-getting-products-properly

For future reference, the SDK now supports `domain` instead of `myShopifyDomain`, and expects the full path to be passed (i.e. "my-store.myshopify.com" instead of "my-store") as of [version 0.2.0](https://github.com/Shopify/js-buy-sdk/releases/tag/v0.2.0). We're currently updating docs to reflect this deprecation.
