### ISSUE TITLE
webpack iconv-loader crashes app

### ISSUE THREAD

**Issue by rkoberg** [Shopify/js-buy-sdk#213]
I got the following error after importing Shopify:
```
./~/encoding/lib/iconv-loader.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/encoding/lib/iconv-loader.js 9:12-34
```
I was getting worse errors and found that I needed a json-loader for webpack to get a little further, but there is still a critical error and Shopify does not work. The hack-around I am using is here: https://github.com/andris9/encoding/issues/16#issuecomment-192161073

**Comment by RoryDuncan** [comment]
I ran into this issue, as well.

In case someone else runs into the problem, and needs another solution:

Load the js-buy-sdk via CDN, inside of a script tag, and added it to webpack config as an `externals`:

``` js
module.exports = {
  /* ...  */
  externals: {
    'shopify-buy': 'ShopifyBuy'
  }
}
// etc
```

Details on externals can be read via the [webpack `externals` documentation](https://webpack.github.io/docs/library-and-externals.html).

**Comment by mwj8410** [comment]
Possibly a more palatable work-around is to extend the webpack loaders to recognize JSON files.

First run `npm install --save-dev json-loader` then add `{ test: /\.json$/, loader: 'json' }` to the `options.module.loaders` section of your webpack configuration.

**Comment by minasmart** [comment]
Is this an issue for js buy? Or for the encoding module that we depend on?

**Comment by mwj8410** [comment]
I only did brief investigation, but I would say that this is an inherited issue from a required module. Looking at that module's activity, I would not expect any resolution from that end, but I would expect documentation within js buy for how to utilize it with webpack because there is a special consideration.

**Comment by minasmart** [comment]
Can the umd build not be utilized directly inside webpack? `encoding` is a dependency of `node-fetch`, but if you're using this for the web, it should be electing to use `whatwg-fetch`. Can you maybe share a little more of your webpack config? I'm curious why webpack is attempting to pull in the node fetch module.

**Comment by mwj8410** [comment]
It's attempting to pull it in because we are using es6 import statements and a babel loader.

Build processes are not really my area of expertise, but, to the best of my knowledge, the es6 import is getting wrapped in a webpack require call. That resolves with the assumption that the required module is a Node module whose entry point is listed in `package.json` under `main`. In this case, that's pointing at `lib/shopify.js`.

Could we do it in a different way? Sure, but this is an easier approach that results in more consistent code on our end.

**Comment by minasmart** [comment]
If you're installing via `npm`, you should be able to point it to the umd build in `dist`, so like `shopify-buy/dist/<filename>`. We should document this approach, because it's come up enough times. Or better yet just point browser `main` at the `umd` build.

**Comment by mwj8410** [comment]
To fully demonstrate the issue, here is a simple [stubbed app repo](https://github.com/mwj8410/wp-babel-buy). Uncomment line 27 of `wepback.config.js` to see the fix. Also, note that a warning is still emitted to the console.

I'm certainly open to another solution, but it'll be a hard sell when the workaround is one line and an additional loader.

**Comment by minasmart** [comment]
did you try referencing the module under the dist directory? If that works, I'm happy to add a browser main to the package so that webpack works more smoothly.

**Comment by mwj8410** [comment]
No, I did not, but I did try adding a browser entry point to package.json, as well as several pattern adjustments, and had the same behavior each time. I do, however, need to move on.
