### ISSUE TITLE
Build Failed because of 'id' of null

### ISSUE THREAD

**Issue by vidboxwebmaster** [Shopify/js-buy-sdk#220]
I tried to "npm install"
but I have a error:

> ./scripts/prepublish
TypeError: Cannot read property 'id' of null
    at versioner.js:36:38
    at tryCallOne (/Users/johnkim/node_modules/shopify-buy/node_modules/nodegit/node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:37:12)
    at /Users/johnkim/node_modules/shopify-buy/node_modules/nodegit/node_modules/promisify-node/node_modules/nodegit-promise/lib/core.js:103:15
    at flush (/Users/johnkim/node_modules/shopify-buy/node_modules/nodegit/node_modules/promisify-node/node_modules/nodegit-promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

Build failed

Please help!

**Comment by yomexzo** [comment]
@vidboxwebmaster, can you provide details about your environment? OS, node/npm version, version of the `js-buy-sdk` (master branch or a specific tag / sha) you are trying to set up.

Anything that can help to replicate this.

Thanks!

**Comment by vidboxwebmaster** [comment]
Thank you @yomexzo 
OS: Mac OS X El Capitan
Node: v6.5.0
npm: v3.10.3
npm ERR! shopify-buy@0.2.2 prepublish: `node ./scripts/prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-buy@0.2.2 prepublish script 'node ./scripts/prepublish'.

**Comment by yomexzo** [comment]
Thanks for providing that @vidboxwebmaster.

Just took a second look at the error and it has to do with `Git`.

Did you clone this repo? If you did, can you confirm you're running the command from the project root (where you have `.git`).

The problem is because the script is unable to get the `git` head commit here - https://github.com/Shopify/js-buy-sdk/blob/master/build-lib/util/versioner.js#L36.

**Comment by vidboxwebmaster** [comment]
Thank you @yomexzo 
It works well!
