### ISSUE TITLE
Use consistent notation in models

### ISSUE THREAD

**Issue by ShaunSpringer** [Shopify/js-buy-sdk#274]
The SDK is all over the place and not standardized. Javascript is typically camelCase but I see snake_case everywhere too.

Sometimes a Product ID is represented as "product_id" (CartLineItemModel) and sometimes its productId (ProductModel).

The fact that the ProductModel isn't just used in the CartLineItemModel makes me frustrated as well, since it's just a product, that is in the cart with a quantity.

**Comment by minasmart** [comment]
Hey there! Sorry for the inconsistency. 

There used to be a technical reason for why line items were snake case. That reason has since gone away,  however, we can't change the naming without a major version bump. Otherwise we'd break all existing clients consuming this SDK. A naming change wasn't really enough for us to bump a major version, but that fix, along with many other enhancements will be part of our v1 release. 

As for line items being a separate model, they do not represent a product. They represent a variant, a product image, line item price, and quantity. This state doesn't belong on any other model, so line items are the correct representation. This follows the conventions in all of our existing APIs as well as Shopify's liquid template system. 

Thanks for your interest in our SDK, and look for our v1 release in the coming months with an update to line item attribute naming.
