### ISSUE TITLE
fetchRecentCart()

### ISSUE THREAD

**Issue by zhangzlili** [Shopify/js-buy-sdk#290]
I wrote a code to display a shopping cart currently being used. But the page went blank. The code is the following: 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Buy SDK Example -- Cart 001</title>
  <link rel="stylesheet" href="index.css">
  <script src="http://sdks.shopifycdn.com/js-buy-sdk/v0/latest/shopify-buy.umd.polyfilled.min.js"></script>

  <script>
    var client = ShopifyBuy.buildClient({
      domain: ‘address.myshopify.com',
      apiKey: '571fdc5bd4c8fc19e82a2e02ea4d4ab4',
      appId: '6',
    });

    var cart = client.fetchRecentCart().then(cart => {
      $('.cart').addClass('js-active');
    });

  </script>
</head>
<body>
</body>
</html>

Could you please help me out with this?

**Comment by minasmart** [comment]
That snippit is targetting an HTML element with the css class `cart`, and adding the CSS class `js-active`. It doesn't look like you have any HTML elements in your document to set this class on.

**Comment by zhangzlili** [comment]
Please advise me on how to set js-active css class on? Thank you so much!

**Comment by minasmart** [comment]
Your code would set the js-active class on any element that matches the css selector `.cart`. Since there are no matching elements, nothing occurs.

You should take some time to draft out an HTML document that represents your shop and/or cart. After you have some elements, you'll have a place to stick the data retrieved from the js sdk.

For help with this, check out our examples!

[Here's an example of the HTML cart](https://github.com/Shopify/js-buy-sdk/blob/master/examples/cart/index.html#L32-L69)

[This file](https://github.com/Shopify/js-buy-sdk/blob/master/examples/cart/index.js) is the associated javascript that orchestrates the cart elements presentation and data.
