### ISSUE TITLE
what UPSELL & bundle apps work with the JS BUY SDK

### ISSUE THREAD

**Issue by lentfert** [Shopify/js-buy-sdk#364]
We successfully implemented several JS Buy SDK implementations in other platforms, really love where this is going... However, we have an issue with utilizing additional features (i.e. UPSELL & Bundles) as the apps provided expect a FULL Shopify cart to load.. (the JS BUY SDK builds the cart but does not allow to render the cart code, instead you use local storage to retrieve the cart items.. what Apps could work when you action the cart checkout feature, without the full Shopify cart)?

**Comment by minasmart** [comment]
There's two facets to this:

First: These apps don't provide an API for us to access through js buy SDK.

Second: In the [js buy v1 alpha (soon to be v1)](https://github.com/Shopify/js-buy-sdk/tree/v1.0alpha), we support server persisted carts, so if you have an app or cart scripts that modifies your checkout session, they should work with the new version. 

Upsell specifically injects a script into the shopify cart / checkout page, and since js buy leaves it up to you to build your own cart rendering, we can't inject additional scripts.

Does this help explain things?
