### ISSUE TITLE
Cart is not persisting after login. 

### ISSUE THREAD

**Issue by Chr15t1an** [Shopify/js-buy-sdk#366]
My team uses Shopify Plus and we require a login before completing a purchase.
After generating the login URL, visit the link, and logging in, the cart is empty. 
Is there a way to let the user login / create account and keep the items I add to the cart?
Thank you for the help. 
__________
```
`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="http://sdks.shopifycdn.com/js-buy-sdk/v0/latest/shopify-buy.umd.polyfilled.min.js"></script>

<script>
var shopClient = ShopifyBuy.buildClient({
  accessToken: 'token-',
  domain: 'domain.com',
  appId: '6'
});

// fetch a product using resource id
shopClient.fetchProduct(product_id).then(function (product) {
varient_obj = product.variants[0];
//return varient_obj;
    var cart;
    shopClient.createCart().then(function (newCart) {
      cart = newCart;
      // do something with updated cart
      cart.addVariants({variant: varient_obj, quantity: 1}).then(function (cart) {
      // do something with updated cart
    });

    x = cart.checkoutUrl;
    });

});

</script>`
```

**Comment by minasmart** [comment]
Where you're sending your user  to is likely the online store login. Carts are not shared between sales channels (js buy / online store). This is a limitation of our system. The [v1 alpha build](https://github.com/Shopify/js-buy-sdk/blob/v1.0alpha/README.md) of js buy provides access to a server persisted cart, and runs off of our new storefront API. Login isn't supported through js buy, however, you can make the API calls to the storefront API to do just that. The login flow is loosely documented [here](https://help.shopify.com/api/storefront-api/reference/mutation/customeraccesstokencreate). Login may be done using the `customerAccessTokenCreate` mutation, then `checkoutCreate` can make use of the resulting customer, so that the cart and checkout is associated with the customer account. This is still new technology, so if the docs don't cover everything, please feel free to post here for help 😄
