### ISSUE TITLE
Safari fetch is undefined on iphone

### ISSUE THREAD

**Issue by kkmal** [Shopify/js-buy-sdk#390]
Using iOS version 10.0.2
SDK version 0.7,1

Probably a known issue, didn't find anything in the issues section.  But Safari didn't implement native fetch until 10.1? The fetchAllProducts function eventually uses fetch down the line and i noticed that your project brings in whatwg-fetch 0.10.1 as a dependency. However, nothing happens when it makes the fetch call on my mobile phone. 

I resolved this by importing the latest version of whatwg-fetch as a polyfill.

**Comment by minasmart** [comment]
Hi there! This may be a naive question, but what version (or CDN URL) of the ShopifyBuy are you using?

**Comment by kkmal** [comment]
Hey, I’m using version 0.7.1 pulled down through npm.

**Comment by minasmart** [comment]
How are you including the module in your project? If you require only the `main` file, it's not polyfilled. If you require (or import) using this path `import ShopifyBuy from "shopify-buy/polyfilled"`, you'll get the polyfilled version. This is _not_ well documented and should be improved. The reason the main file isn't polyfilled is because we assumed that if you're including this module through NPM, we shouldn't be contaminating your system with a bunch of globals.

Please let me know if this helps.

**Comment by kkmal** [comment]
Yes that answers my question. I should have probably glanced over the dependency structure - I would have noticed the polyfilled files. Thanks!

**Comment by minasmart** [comment]
np! Glad it fixed it, and I'm going to make sure this is documented more clearly. Thanks for bringing this forward!
