### ISSUE TITLE
use of UPsell or discount apps with JS buy SDK

### ISSUE THREAD

**Issue by lentfert** [Shopify/js-buy-sdk#402]
We have implemented several js-buy-sdk based solutions, and they work elegantly (overtime the limitations found in early releases are reduced or eliminated, so AWESOME!) there is one major thing that bothers me with the solution I would like to raise here: many of the customers want to use shopify because of security & control, and the availability of APPS they can use/buy when needed. This applies to discount and upsell apps as well, however NEITHER work using the buy-sdk, as they require a shopify cart, the buy SDK does not engage at this level, and only hands to shopify with checkout-url, how can we benefit from these apps? building it from scratch seems crazy. Any solutions?

**Comment by minasmart** [comment]
These apps don't provide us with public APIs to connect to. If the app integrates in your checkout, it can be accessed there. Otherwise, there's no solution I know of, since the purpose of this library is to have an off-shopify storefront.

If the apps you'd like use provide public APIs, integrating with them would be the best option.

**Comment by firescript** [comment]
Hey @minasmart is there anyway for a buy button user to be able to benefit from more than just one single coupon code discount? I love the idea of writing scripts, so that i can enable (if product a is in cart and product b is as well give product b 50% off) but these scripts don't seem to take effect on my checkout that the buy button cart takes me to. However on the shopify store checkout the scripts work fine and automatically generate the discount. 

Is there any way for me to elevate the buy button experience? Could the storefront api help with this? Looking for clarity as the site we've built is on WordPress and moving to a full shopify store is not an option.
