### ISSUE TITLE
Issue with webURL missing checkout.shopify.com?

### ISSUE THREAD

**Issue by youanden** [Shopify/js-buy-sdk#407]
Cross posting issue from [here](https://github.com/Shopify/graphql-js-client/issues/95).

Seems like checkout object returned when adding line items is returning a malformed url.

For example:
```https:///{shopifyStoreId}/checkouts/{checkoutId}?key={key}```

It has been doing that for approximately 3 hours now.

I know this comes with the beta but it seems like the API is stable and I checked the graphql response. It came directly from the API and wasn't modified by the client.

Let me know if you need me to provide more info. I'd be happy to submit a bug report with actual cart IDs, request query, etc.

**Comment by minasmart** [comment]
Hey there, are you working with the beta or alpha branch? There are no tagged releases on the beta branch because the API is currently be re-worked. 

That said, the alpha branch should be safe to use. There haven't been any releases for a few days. Can you provide exact version info, and a code snippet?

Thanks!

**Comment by minasmart** [comment]
Sorry, do you mean directly from the storefront API?

**Comment by swalkinshaw** [comment]
@youanden can you be a little more specific about the before/after URL format? (without providing sensitive info of course).

There actually was a change deployed to do with checkout URL generation today so maybe this caused a regression.

**Comment by Gomah** [comment]
I've had the same issue at the same time (~7am to ~9.30am AEST time)

Following @youanden example, the `shopifyStoreId` was replaced by an ip address, in my case:

```
https://0.123.156.213/checkouts/${token}?key=${key}&discount=XXX
```

Fortunately, it started working again around 9.30am but I could not notice any incidents related to this issue on the [status page](https://status.shopify.com/).

Note:
- I use a custom checkout domain.
- I tested on multiple stores (with & without custom checkout domain) & reproduced the issues.

**Comment by swalkinshaw** [comment]
Thanks for the report @Gomah. We're looking into this to see if there was a known issue.

**Comment by swalkinshaw** [comment]
@Gomah and @youanden I confirmed there was an issue yesterday with checkout URLs matching up with what you experienced.

The regression was fixed at roughy 7PM EST. It looks like an incident wasn't reported on our status page because the scope was believed to be quite small and we hadn't received any reports during that time (these came after it).

Sorry for the inconvenience and troubles.

**Comment by Gomah** [comment]
@swalkinshaw Thanks for the update!
