### ISSUE TITLE
variantForOptions alway sreturning undefined

### ISSUE THREAD

**Issue by Jimtattersall** [Shopify/js-buy-sdk#428]
When using variantForOptions it always returns 'undefined' as if no match is found.
```
    client.fetchQueryProducts({ handle: window.product }).then((product) => {
      console.log(Client.Product.Helpers.variantForOptions(product[0], { 'Size': 'S' }))
    })
```
This logs "Undefined" the product has variants with the Size option of 'S'
product[0] when logged returns a valid Object

**Comment by Jimtattersall** [comment]
Apologies it turns out all the options need to be passed.

```
    client.fetchQueryProducts({ handle: window.product }).then((product) => {
      console.log(product[0])
      console.log(Client.Product.Helpers.variantForOptions(product[0], { Size: 'S', Color: 'Navy Heather', Category: 'Tops' }))
    })
```

Is it possible to pass a partial match ?

**Comment by minasmart** [comment]
It isn't, because a partial match could be an unbounded set of variants. Returning an array from this method with all variants that match just one option would increase the complexity for the caller. They'd have to handle both an array without a meaningful value, and a concrete instance of a variant.
