### ISSUE TITLE
Add collections data to ProductModel

### ISSUE THREAD

**Issue by evvvritt** [Shopify/js-buy-sdk#436]
Hi, I'd like to organize my products by collection in my web-app. 

However, because there isn't any collections data in the ProductModel, it seems I have to `fetchAllCollections` and then loop through each collection and `fetchQueryProducts` all of their products.

If products included some collections data I could simply `fetchAllProducts` and sort them in my app. At least `title` and `ID` (+ thumbnail?) would be great.

Thanks!

**Comment by minasmart** [comment]
Our API doesn't work that way, because a product can be in an unlimited set of collections, meaning a product model could become very very large.

This is however, not ideal. If you'd like to try out our [beta](https://github.com/Shopify/js-buy-sdk/tree/v1.0beta), currently installable via npm with the version `1.0.0-beta.3`, there's a `client.collection.fetchAllWithProducts(first = 20)` method, which will return the first 20 collections, with the first 20 products from each of those collections.

This beta looks like what our `1.0` release will look like. For help in switching over, there's a [migration guide](https://github.com/Shopify/js-buy-sdk/blob/v1.0beta/docs/MIGRATION_GUIDE.md), and [api reference](https://github.com/Shopify/js-buy-sdk/blob/v1.0beta/docs/API_REFERENCE.md) to help you get started.

**Comment by evvvritt** [comment]
(Thanks for the info and quick reply!)

Beta looks promising! I still think having an array of title's and ID's wouldn't be too large. (One could already add an infinite amount of tags right?)

But thanks for hearing my request.

**Comment by minasmart** [comment]
We don't commonly see an infinite amount of tags, but we do commonly see a product in over 10k collections, so it is a concern.
