### ISSUE TITLE
No formatted_price?

### ISSUE THREAD

**Issue by richgcook** [Shopify/js-buy-sdk#461]
I'm struggling to see how to pull out the formatted_price when fetching all products? See screenshot of my log of products.

<img width="818" alt="screen shot 2017-12-18 at 19 27 35" src="https://user-images.githubusercontent.com/901289/34124111-abf46c9c-e429-11e7-8f8b-5cd5ae0aaf45.png">

**Comment by minasmart** [comment]
There's really no nice way to do this, because formatting money is a function of locale, and we don't know the client locale. The shop resource provides a `moneyFormat` string, which is the money format that's been set for online store, and can be used for interpolation, but it still won't represent client locale. We also provide a `currencyCode` on the shop resource.

Your best bet to do this accurately is to use `toLocaleString` like:

```javascript
parseFloat(variant.price).toLocaleString(navigator.language, {style: 'currency', currency: shop.currencyCode})
```
