### ISSUE TITLE
Fetch a product's collection(s) to build 'Related Products'

### ISSUE THREAD

**Issue by richgcook** [Shopify/js-buy-sdk#464]
You cannot get the collection(s) a product is in using `client.product.fetch` – this is useful to build Related Products etc. Any thoughts?

**Comment by minasmart** [comment]
This SDK is built using the [storefront API](https://help.shopify.com/api/storefront-api/reference), which is built in graphql. That means that the resulting data is an object graph, and most relationships can be exposed in cycles. Exposing this through an SDK is difficult, because we have to ask how far to go in showing nested relationship upon nested relationship. The other downside is that the more varied queries we have for different cases, the larger the SDK gets in terms of payload size. If you have very specific use cases, I would recommend using the API directly, with either [Shopify's data driven graphql javascript client](https://github.com/shopify/graphql-js-client), or the relay or apollo UI driven clients for graphql. This SDK only exposes a portion of the available functionality of that API hedging on simpler uses cases. Complex or highly specific use cases should be orchestrated using the API directly.

**Comment by richgcook** [comment]
@minasmart Thanks for this, Mina. I had no idea the SDK was for simpler uses cases to be honest so thanks for clearing up.
