### ISSUE TITLE
shopClient.fetchProduct() is not a function

### ISSUE THREAD

**Issue by Mobashir1995** [Shopify/js-buy-sdk#479]
I'm using js buy sdk v1. Here is my code, which I'm using
```
<script src="http://sdks.shopifycdn.com/js-buy-sdk/v1/latest/index.umd.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
<script type="text/javascript">
	var shopClient = ShopifyBuy.buildClient({
	   domain: 'dev-shopify-1.myshopify.com',
	   storefrontAccessToken: 'f5804896b99f194bfbe2fa26b6026cae',
	});

	shopClient.fetchProduct('11152205396').then(function(product){
		console.log(product);
	});
</script>
```

But it shows error like **TypeError: shopClient.fetchProduct is not a function**

can anyone tell me what is the problem, and how can I fix it?

**Comment by minasmart** [comment]
That's expected behaviour. The fetch methods are all namespaced under their resource type.

The method you're looking for is `shopClient.product.fetchAll()`. There's docs linked from the Readme, and in the source, [here](https://github.com/Shopify/js-buy-sdk/blob/master/src/product-resource.js#L21-L32L)

**Comment by Mobashir1995** [comment]
yes, now it's working. Thanks @minasmart  a lot. You are really a very helpful lady....
