### ISSUE TITLE
Please provide TypeScript definition file

### ISSUE THREAD

**Issue by brunolm** [Shopify/js-buy-sdk#504]
Nowadays it's possible to ship a TypeScript definition file with the package, you only need two things:

- create a `.d.ts` file with your package definitions, example from `moment`
https://github.com/moment/moment/blob/develop/moment.d.ts

- add `"typings": "./your-file.d.ts",` in package.json, example from `moment`
https://github.com/moment/moment/blob/develop/package.json#L27

**Comment by minasmart** [comment]
Feel free to make a PR! I don’t think we’ll be focusing on that soon.

**Comment by Totemika** [comment]
I am currently consuming this library with TypeScript and I am very interested and motivated to collaborate so we can have correctly versioned Typings.

**Comment by darol100** [comment]
Hey @brunolm,

Just out curiosity what are the benefits of providing a TypeScript definition file on a project that is not written in TypeScript?

**Comment by ergoposti** [comment]
@darol100 

The same benefits as using typescript over javascript. Better intellisense, less runtime errors etc.

**Comment by Weffe** [comment]
I might be looking to use TypeScript with this library in the near future and noticed the supported version on the @types repo is on `v1.4.0` while the latest release is on `v2.2.4`. Would Shopify be willing to provide updated types directly from this repo instead of the @types repo? That way the typings don't go stale as they did for the current version.

**Comment by chase-moskal** [comment]
> add "typings": "./your-file.d.ts", in package.json, example from moment

nowadays we use the `types` field instead of the older deprecated `typings` field

i'm sure the fine folks at shopify would be happy if somebody could create a PR to add the typescript typings, so long as they were complete and correct

it would be even better to convert the sourcecode to typescript so that we can guarantee that the codebase is actually in-line with the provided typings

:wave: Chase

**Comment by Weffe** [comment]
Going off my gut but I think it's better time spent updating the existing types on the `@types` repo ([see here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/shopify-buy)) rather than trying to add updated types directly into this repo. It doesn't seem like TypeScript support is a big priority for this repo, especially since this issue has been open for well over a year!. Plus, maintaining those types would probably be a community effort like it's always been. So I think it's best to try and update the already existing types. I'll take a crack at updating the existing types when I get the time.

**Comment by PierreAndreis** [comment]
I got started on updating the typings, but still a long way to go. The API has changed a lot since it was last updated (or the typings were just not accurate?)
You can check it out [here](https://github.com/PierreAndreis/DefinitelyTyped/commit/753a37b130c8a274fa0e14c41c2404e8edb2a985)
Feel free to fork or contribute on that branch.

**Comment by Weffe** [comment]
Nice, I'll contribute to your fork!

**Comment by Weffe** [comment]
This hasn't been forgotten! Piggy backing off the initial changes @PierreAndreis did. I feel confident that I am 99% done. I just need to actually test these new types against an actual Shopify shop. 

https://github.com/Weffe/DefinitelyTyped/tree/shopify-buy-2.6/types/shopify-buy

**Comment by PierreAndreis** [comment]
@Weffe this is beautiful! Thank you so much for your effort. Let's get that merged up so other folks can start using on their project and with time we can reach that 100%. 👏👏👏

**Comment by Weffe** [comment]
@PierreAndreis Could you open a separate issue with your problem (I got more questions to bring up that relates to your problem)? I don't think we should continue using this thread as it's not really in this Issue's scope

**Comment by rebeccajfriedman** [comment]
Closing this as stale.

**Comment by chase-moskal** [comment]
@rebeccajfriedman, @Weffe, @PierreAndreis — what's the current status of this issue?

we should add a `types` field to the package.json in this repository, so that the types just come with the package for typescript users

**Comment by Weffe** [comment]
@chase-moskal Been way too busy lately and hadn't had a chance to finish the updated typings. Getting them added here in the repo would be nice so that this package includes them out of the box. But then it would have to be on the maintainers to consistently update the types on each release. If it's on DefinitelyTyped, then it's maintenance is delegated to the community. At least that's the way I see it. It wouldn't make sense to me to include types in this package if they're going to become incorrect due to the maintainers not updating them consistently.

What are your thoughts on that?

**Comment by stuffedmotion** [comment]
TS support would be great. Currently the types seems to be out of sync with the package

**Comment by balibebas** [comment]
> Just out curiosity what are the benefits of providing a TypeScript definition file on a project that is not written in TypeScript?

Type safety.

**Comment by balibebas** [comment]
> Just out curiosity what are the benefits of providing a TypeScript definition file on a project that is not written in TypeScript?

Type safety. Not to mention Intellisense which is probably the biggest developer productivity boost since ES2015 modules.

**Comment by balibebas** [comment]
> Just out curiosity what are the benefits of providing a TypeScript definition file on a project that is not written in TypeScript?

Type safety. Not to mention Intellisense which is probably the biggest developer productivity boost since DevDocs.

**Comment by chase-moskal** [comment]
@itsdarrylnorris, @rebeccajfriedman — these days it's only responsible to maintain types for a serious javascript library. for typescript users (which seems to be most devs these days), consuming an untyped library is annoying and stinky

@Weffe — i agree with you. i think the correct path is either definitely typed, or even better, converting the sourcecode to typescript to cut all the maintenance.. the only thing worse than no types is outdated types

this codebase looks relatively small. would the maintainers of this library consider merging a PR to convert the sourcecode to typescript? this would totally eliminate the community's maintenance burden of manually keeping the types up to date, win win

**Comment by balibebas** [comment]
Opened for visibility: https://github.com/Shopify/js-buy-sdk/issues/770
