### ISSUE TITLE
The Storefront API only works in the context of a sales channel app? 

### ISSUE THREAD

**Issue by abhilash29** [Shopify/js-buy-sdk#514]
@swalkinshaw told me in my previous post (https://github.com/Shopify/js-buy-sdk/issues/509#issuecomment-380838837) that **The Storefront API only works in the context of a sales channel app**

However, I would like to inform that I've been using the StoreFront API successfully with the store front access token that I generated through the admin panel without enabling the sales channel.
The issue basically happens only if I created the StoreFrontAPI token via. REST API.
So is it something like enabling sales channel is a requirement to access the Store Front API only if I want to create a StoreFront access token via. REST API and not otherwise. By otherwise I mean "creating the storefront access token via. admin panel"

**Comment by swalkinshaw** [comment]
As mentioned in the other issue, we automatically make your private app a channel if you enable Storefront API. We have to do that otherwise it wouldn't work at all 😄 

Our docs have been updated to reflect the requirements of a sales channel if you create tokens via the REST API: https://help.shopify.com/api/storefront-api/getting-started#authentication
