### ISSUE TITLE
How to get a demo running?

### ISSUE THREAD

**Issue by Codesesh** [Shopify/js-buy-sdk#519]
I'm trying to follow the docs to get a basic demo going. I am trying to integrate this into a PHP site. I have 

`npm install shopify-buy`

do we then need to include the file like 

`<script src="node_modules/shopify-buy/index.js"</script>`

I have a babel complier, but it is throwing an error saying I need requireJS?

To me the instructions on the docs aren't that clear.

It is possible to do a codepen demo?

**Comment by minasmart** [comment]
To quote the docs:

There is a minified UMD build available via CDN:

```html
<script src="http://sdks.shopifycdn.com/js-buy-sdk/v1/latest/index.umd.min.js"></script>
```

## Builds
The JS Buy SDK has four build versions: ES, CommonJS, AMD, and UMD.

**ES, CommonJS:**
```javascript
import Client from 'shopify-buy';
```
**AMD:**
```javascript
import Client from 'shopify-buy/index.amd';
```
**UMD:**
```javascript
import Client from 'shopify-buy/index.umd';
```

If you're referencing a package directly from the node module, use the version that suits your environment. If you don't have a module system, use the UMD build, since UMD modules fall back to globals. Similarly, use the CDN referenced if you're just including this as a script in the DOM to get the latest `v1` UMD build.
