### ISSUE TITLE
Search products by title (result = all products that contain string)

### ISSUE THREAD

**Issue by lisadreamer** [Shopify/js-buy-sdk#529]
In order to have Search input field which would return all products that match to search string. (smth similar to: WHERE TITLE LIKE 'jeans%')

As far as I understood right now there is only 
client.product.fetchQuery({first: 20, sortKey: 'CREATED_AT', reverse: true, query: 'title:jeans'})
but it would return products with exact title not like.

i saw also in "product connection" argument "after" which would be possible to somehow use in order to create such search functionality but "js buy sdk" fetchQuery doesnt have it.

Correct me if I understood it wrong) 
Recommendations? 
Should I use for it graphql-js-client?

**Comment by Alligatore3** [comment]
@swalkinshaw is it possible to implement [predictive search](https://shopify.dev/docs/themes/ajax-api/reference/predictive-search) ?

I have my [public REST API](https://jamteam.myshopify.com/search/suggest.json?q=Bre&resources[type]=product) and I want to perform a simple GET with fetch API but I can't fix CORS problem.
CORS is due to different domain since I'm working in localhost (of course), is there anything I can do about it ?
