### ISSUE TITLE
Error using first in the query parameters "Variable first of type Int! was provided invalid value"

### ISSUE THREAD

**Issue by gsalgadotoledo** [Shopify/js-buy-sdk#552]
When I try to retrieve a list of product using first in the query parameters

**To Reproduce**
do this:

```
this.props.client.product.fetchAll({ first: 250 }).then((products) => {
  ..
})
```

If I pass the parameter this way, it works fine
```
this.props.client.product.fetchAll(new Number(250)).then((products) => {
  ..
})
```

**Comment by minasmart** [comment]
[the signature for `fetchAll` receives a primitive integer, not a hash](https://github.com/Shopify/js-buy-sdk/blob/master/src/product-resource.js#L32).

In the future: please follow our [issue template](https://github.com/Shopify/js-buy-sdk/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) so that we can properly determine what version of the SDK you are using, what platform the bug is occurring on, and agree to our code of conduct, etc.
