### ISSUE TITLE
Pagination is not working / API inconsistent (or docs are misleading?)

### ISSUE THREAD

**Issue by noambonnie** [Shopify/js-buy-sdk#559]
**Describe the bug**
Trying to paginate all products, I keep failing - `client.fetchNextPage()` doesn't return anything
`products.hasNextPage` is undefined. `products[0].hasNextPage` exists though.

What am I doing wrong?

**To Reproduce**
```
// I have more than 5 products... 
let products = await client.product.fetchAll(5);
// This part prints the first page as expected.
products.forEach((item) => {
    console.log(`${item.id} ${item.variants[0].available} (${item.variants.length}) ${item.title} ${item.variants[0].id} ${item.images != null? "image":"no image"}`);
})

// products.hasNextPage is undefined in the following print
console.log(`Has next page: ${products.hasNextPage}`) 

products = await client.fetchNextPage(products);

// This same loop as above now fails ("products.forEach is not a function")
products.forEach((item) => {
    console.log(`${item.id} ${item.variants[0].available} (${item.variants.length}) ${item.title} ${item.variants[0].id} ${item.images != null? "image":"no image"}`);
})
```

**Expected behavior**
Fetching the next page and then iterating through the products should fetch new products and allow iteration as with the first page.

**Environment (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser N/A
 - SDK Version 1.8.0
 - nodejs v8.9.1

**Additional context**
For the love of me, I couldn't find a simple, straightforward example of fetching all products with pagination (or any other pagination using the buy-sdk models). I gave up back in March and we limited our store to 15 items. But that's obviously not a sustainable solution :-)

Can anyone please provide an example of how to loop over paginated results of a model? (products, checkout line items etc.)

**Bug Report Checklist**
- [X] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [X] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [X] I have provided a detailed description of the bug, including code samples, and/or network data.
- [X] I have provided information about my development environment, including SDK version.

**Comment by StefanSlehta** [comment]
Hi @noambonnie !
`let products = await client.product.fetchAll(5);` -> This will return an `Array` of [`GraphModel` ](https://github.com/Shopify/graphql-js-client/blob/master/src/graph-model.js) objects. (Hint: `js-buy-sdk` uses [graphql-js-client](https://github.com/Shopify/graphql-js-client) in the background).
That's why the next line: 
```
products.forEach((item) => {
    console.log(`${item.id} ${item.variants[0].available} (${item.variants.length}) ${item.title} ${item.variants[0].id} ${item.images != null? "image":"no image"}`);
})
```
Works fine, since [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) is defined for an `Array`.

After, ``console.log(`Has next page: ${products.hasNextPage}`) `` doesn't work because `products` is of type `Array` and array doesn't know about `hasNextPage` but `GraphModel` knows about it (as you mentioned `products[0].hasNextPage` works). 

`Object.prototype.toString.call(products); // [object Array]`
`Object.prototype.toString.call(products[0]); // [object Object]`

`products = await client.fetchNextPage(products); ` returns a GraphQL response. You can access your array of products via `products.model` so change the next line to:
```
products.model.forEach((item) => {
    console.log(`${item.id} ${item.variants[0].available} (${item.variants.length}) ${item.title} ${item.variants[0].id} ${item.images != null? "image":"no image"}`);
})
```
Hope this helps!

**Comment by noambonnie** [comment]
Thank you @StefanSlehta - I could swear I tried what you suggested before only to get the same first page. But I tried it again now and it works. Still not a fan of the inconsistency in returned results... But I can definitely live with it. 

Thanks!

**Comment by StefanSlehta** [comment]
No problem! If you find a concise example for pagination or simply want to improve the docs, please feel free to submit a PR !

**Comment by darkrubyist** [comment]
Here is an example that works for me.

```
const flatten = function(arr) {
  return Array.prototype.concat.apply([], arr);
}
```

```
let allProducts = [];   
let data = await client.product.fetchAll(250);
let hasNext = data[data.length - 1].hasNextPage
allProducts.push(data)

while (hasNext == true) {
  new_data = await client.fetchNextPage(data)
  data = new_data.model
  hasNext = data[data.length - 1].hasNextPage
  allProducts.push(data) 
}

const products = flatten(allProducts)
```
