### ISSUE TITLE
Creating checkout fails with nondescript "UserError"

### ISSUE THREAD

**Issue by freder** [Shopify/js-buy-sdk#593]
this is a follow-up to #582

enabling all the permissions did indeed fix the `access denied` issue, but it still doesn't work.

```
await client.checkout.create()
    .then((checkout) => {
        console.log(checkout);
    })
```

results in:

```
GraphModel {
  ...
  errors: undefined,
  userErrors:
   [ type: { name: 'UserError',
       kind: 'OBJECT',
       fieldBaseTypes: [Object],
       implementsNode: false } ] }
```

what does that mean exactly?

---

`shopify-buy v1.10.0`

**Comment by minasmart** [comment]
Can you stick a `.catch` on your promise and see what the error is that gets passed?

**Comment by freder** [comment]
@minasmart well `.catch()` is never called. it simply logs `checkout`.

**Comment by minasmart** [comment]
Sorry, I misunderstood the initial problem. I'm not entirely sure what the problem is. The checkout will be a `GraphModel` type. The model that's yielded should have the attributes of a checkout. For a list of attributes, check out the [checkout query](https://github.com/Shopify/js-buy-sdk/blob/master/src/graphql/CheckoutFragment.graphql).

There may be a problem here with your `await`. Await will return the resolved value of the promise, and right now your promise is resolving, but the `then` isn't returning anything for the `await` to capture. Typically, you'd have an assignment with an `await`, and then on the next line stuff to do, **or** a `then` where things happen in the passed in function.

**Comment by freder** [comment]
ok, this seems to work. – I think I was just thrown off by that `userErrors` field
