### ISSUE TITLE
I've recently been able to access the tags of individual products

### ISSUE THREAD

**Issue by alexstolznut** [Shopify/js-buy-sdk#602]
**Describe the bug**
Within the past few days I have not been provided with the tags of an individual item.

**To Reproduce**
Steps to reproduce the behaviour:
```
`      var client = window.ShopifyBuy.buildClient({
            domain: 'yongtai-ginseng.myshopify.com',
            storefrontAccessToken: 'token'
        });

        //create a checkout instance so the customer can add
        //items to their carts
        var checkout;
        client.checkout.create().then((c) => {
            checkout = c;
        });

     client.product.fetchAll(250).then((products_complete) => {
     var i;
     for (i = 0; i < products_complete.length; i++) {
         let product_tmp = products_complete[i];
         window.console.log(product_tmp);
    }
}`
```

<img width="502" alt="screen shot 2018-12-01 at 12 40 52 am" src="https://user-images.githubusercontent.com/7701214/49326121-2720c980-f502-11e8-83c9-d2aaf3bbf97d.png">
Yet no tags or types are provided to me even though they are visible within the shopify store.

**Expected behavior**
I would expect there to a tag or tags key somewhere within the object

**Environment (please complete the following information):**
 - SDK Version [e.g. `v1/latest`]

**Additional context**

**Bug Report Checklist**
- [x] I have read and agree to the [CODE_OF_CONDUCT.md](https://github.com/Shopify/js-buy-sdk/blob/master/CODE_OF_CONDUCT.md)
- [x] I have read the [CONTRIBUTING.md](https://github.com/Shopify/js-buy-sdk/blob/master/CONTRIBUTING.md) guidelines.
- [x] I have provided a detailed description of the bug, including code samples, and/or network data.
- [x] I have provided information about my development environment, including SDK version.

**Comment by joeserg** [comment]
I'm having the same issue. It's working in a deployment where I haven't ran `npm update`, but a new instance is exhibiting the same behaviour. If it makes a difference, I'm using `collection.fetchAllWithProducts()`, rather than `product.fetchAll()`. I've also confirmed that my Storefront API Token still has the 'Read product tags' permission enabled.

**Comment by rebeccajfriedman** [comment]
As described in our [Changelog](https://github.com/Shopify/js-buy-sdk/blob/master/CHANGELOG.md#v1110-november-27-2018), this was removed in version `1.11.0`. In the immediate term, you can lock to version `1.10.0`, and it will give you back tags. In the medium term, we are investigating how to make our SDK more flexible so that it will be easy to generate custom queries (so you can add back in the `tags` field). Sorry for any inconvenience that this has caused.

Here's a link to the CDN url: `https://sdks.shopifycdn.com/js-buy-sdk/1.10.0/index.umd.min.js`

**Comment by alexstolznut** [comment]
Thank you for providing the link to the previous CDN and explaining this all. It really means a lot.
