### ISSUE TITLE
Fetch tags from collection

### ISSUE THREAD

**Issue by rafauke** [Shopify/js-buy-sdk#632]
Hey guys,

For starters, thanks for great lib! Really useful :) I have one problem now, though. I would like to reflect filtering functionality in my app using the Shopify JS SDK. I'm fetching all collections properly, along with their products, all looks cool. However, in order to filter out products inside collection I would like to know what tags I can filter through in this collection. Can you tell how this could be implemented? I could recursively collect all the tags in collection from products contained in it, however this does not look like a proper solution to the problem. Also, this is not possible, because `products` don't have the `tags` field in it. So the question is:

1. Where to find info about tags in given collection?
2. How to add `tags` info to products returned by `fetchWithProducts`?  I guess that `product.fetchQuery` could be used for that, this however involves another request and doesn't answer the fact that I don't have the tag to query with :)

I would appreciate any tips and suggestions, thanks!

**Comment by rebeccajfriedman** [comment]
👋Unfortunately, we don't support a way to fetch tags across a collection. I would suggest aggregating all the tags yourself (like you suggested). Additionally, there is a method in the Storefront API that [fetches all product tags across the shop](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/queryroot#producttags), so perhaps that would be more useful?

You're right that tags are not returned in `fetchWithProducts`. This is because returning tags requires an access scope (`unauthenticated_read_product_tags`), which not all shops use. There is a [section in the README](https://github.com/Shopify/js-buy-sdk#expanding-the-sdk) which explains how to write custom queries (which can expose whichever fields you need). I'm going to close this issue, but feel free to open a new one if you have any questions about writing custom queries.
