### ISSUE TITLE
Ability to Send products to main website cart instead of dynamic cart URL

### ISSUE THREAD

**Issue by sendy34** [Shopify/js-buy-sdk#666]
We have a scenario where we use Shopify Buy JS for on 2-3 products. So we have created an Proxy app, where we use Shopify JS Buy SDK. This app pulls products from collections of main website.

But main website has it's own cart, and the cart created by the Proxy App is always different since it's checkout URL is created dynamically.

Is there any way so that we could send the products users bought on Proxy app to the main website cart.

**Comment by morganmccunn** [comment]
There is no way to send the products to the same cart as your main website (ie. your online store).

An app using the buy SDK counts as a channel. Channels don't have access to each others carts (both for security, and clarity with publications, since all products in a cart from one channel may not be available on another channel).
