### ISSUE TITLE
How to add lineitem with custom price?

### ISSUE THREAD

**Issue by akkivaghasiya5** [Shopify/js-buy-sdk#708]
I'm developing an app in which I have to add a lineitem with custom price.

e.g, Product price is 700. But I have to sell the product at price of 500 in some cases, at 400 in some other cases, etc. But I'm not getting any way to add lineItems with this config.

This SDK provides [checkout.addLineItems()](https://shopify.github.io/js-buy-sdk/checkout-resource.js.html#line141) function. But I can only pass the variantId and quantity. I can not change/update the price.

Shopify Orders Rest API provides this option while creating the order ([Create a comprehensive order](https://help.shopify.com/en/api/reference/orders/order#create-2019-07)). So feature to add lineitem with this config also should be available. But it's only either I can not find the correct way or it's not implemented in the SDK.

So, is there any way to update the price of the lineitem?

**Comment by rebeccajfriedman** [comment]
The Storefront API does not allow price overrides because it is a [public and unauthenticated API](https://help.shopify.com/en/api/storefront-api#using-an-unauthenticated-public-api). You should be able to accomplish similar functionality using [automatic discounts](https://help.shopify.com/en/manual/promoting-marketing/discount-codes/automatic-discounts), or [script discounts](https://help.shopify.com/en/manual/apps/apps-by-shopify/script-editor) (Plus-only).
