### ISSUE TITLE
Support for inventory quantity

### ISSUE THREAD

**Issue by peeppirnpuu** [Shopify/js-buy-sdk#753]
Hey, great job maintaining the libarary!

Curious to hear when could we access the product variant's `quantityAvailable` field?
https://shopify.dev/changelog/inventory-quantity-available-on-storefront-graphql-api

[Link to API reference](https://shopify.dev/docs/storefront-api/reference/object/productvariant?api%5Bversion%5D=2020-04)

**Comment by arobbins** [comment]
I was just looking for this last night. Support for this would be amazing!

Is anyone taking pull requests to make this happen?

**Comment by arobbins** [comment]
Quick update on this.

I've forked the repo and followed the contribution guide to attempt a pull request for this change. I'm _assuming_ it simply requires updating the `VariantFragment` and graphql schema. however I'm not too confident about that :)

I've tried updating the package locally with the above changes but still receive the error:

```
Field 'quantityAvailable' doesn't exist on type 'ProductVariant'
```

I wonder if @StefanSlehta or @rebeccajfriedman could offer some guidance on which files to edit. Happy to do the work to make it happen.

**Comment by StefanSlehta** [comment]
Hi, Sorry for the delayed response

@arobbins The issue is that we're still on `2020-01` schema, which doesn't support the `quantityAvailable` field. I've opened a [PR](https://github.com/Shopify/js-buy-sdk/pull/755) to update the api version which should allow you to pull this field in and open a PR for it!

**Comment by arobbins** [comment]
@StefanSlehta Awesome thank you!

**Comment by StefanSlehta** [comment]
Hey just an update, you can also [expand](https://github.com/Shopify/js-buy-sdk#expanding-the-sdk) the queries you'd like to use instead of adding to the `VariantFragment `.
We'll have to determine if adding `quantityAvailable` for everyone makes sense at the moment, mainly because fetching surplus fields starts slowing down the library for everyone even if they don't need all the fields. By expanding certain queries you can fetch exactly the things you need and still keep it relatively quick. 
Hope this helps!

**Comment by arobbins** [comment]
@StefanSlehta 

Thanks for the direction. 

I managed to get the `quantityAvailable` field pulled in successfully this morning. I'm using the unoptimized UMD bundle and expanding the main query like you mentioned. Works great!

However I have two more questions now:

1. To get this to work, I needed to fetch the master branch, run a build, and then include the UMD bundle that way. Can we get this change pushed to a new `2.9.4` release? That way I can continue importing the package like normal. I definitely don't want to include an unoptimized build in my final product. 

Since I'm expanding the query I wouldn't need to submit a PR.

Thanks again!

**Comment by StefanSlehta** [comment]
Just updated to `2.10.0`, npm is there, CDN might take up to ~24h to bust the cache.

**Comment by arobbins** [comment]
You rock!

**Comment by wirsing** [comment]
@arobbins @StefanSlehta Thanks for this! Would you guys mind posting a short example on how to expand the query to pull the inventory field? I checked the link but can't get the query right. Thanks!

**Comment by obelmont** [comment]
> @arobbins @StefanSlehta Thanks for this! Would you guys mind posting a short example on how to expand the query to pull the inventory field? I checked the link but can't get the query right. Thanks!

I'm building a static site (nextjs) that uses a useEffect hook to pull the available qty.
Below is the extended query I use to get this data.
Keep in mind that if the quantityAvaliable returns null it just means that the product's qty is not tracked!

```js 
const productAvailableQty = (handle) => {
  const qtyQuery = shopify.graphQLClient.query((root) => {
    root.add(
      "productByHandle",
      { args: { handle: `${handle}` } },
      (product) => {
        product.add("title");
        product.add("handle");
        product.add("id");
        product.addConnection(
          "variants",
          { args: { first: 99 } },
          (variant) => {
            variant.add("id");
            variant.add("availableForSale");
            variant.add("quantityAvailable");
          }
        );
      }
    );
  });
  return shopify.graphQLClient
    .send(qtyQuery)
    .then((res) => JSON.parse(JSON.stringify(res.model.productByHandle)))
    .catch(() => null);
};

**Comment by 50bbx** [comment]
@obelmont what do you mean by saying that the quantity is not tracked?

**Comment by obelmont** [comment]
@50bbx It means that the product's available inventory is not tracked in Shopify. It's an option in the Inventory section of each product in Shopify's admin panel that is used to determine available stock to ensure you don't sell more than you have.

**Comment by socreative** [comment]
@obelmont _I get No field of name "quantityAvailable" found on type "ProductVariant" in schema_  when I run the query :(

**Comment by ktaftaf** [comment]
@socreative try `inventoryQuantity`

**Comment by city17** [comment]
@ktaftaf That's for the regular Shopify API, [Storefront uses `quantityAvailable`.
](https://shopify.dev/docs/storefront-api/reference/products/productvariant)
@socreative I also get the same: Error: No field of name "quantityAvailable" found on type "ProductVariant" in schema. 

I do have the correct access in the Shopify App as I can query the quantityAvailable field with a standard GQL query at build time.

@obelmont Could you confirm that your code is still working for you? Trying the same code results in the schema error for me...

**Comment by kolorfilm** [comment]
I have the same problem. Tried to access quantityAvailable from variant and it seems it is not in there.

**Comment by Mritunjay004** [comment]
I have provided both read_inventory access in the storefront and tracking the quantity still getting `quantityAvailable: null`. Someone help please.

**Comment by kolorfilm** [comment]
There is also no **quantityAvailable** within the data **item.variant**. There isn't even quantityAvailable at all.

<img width="828" alt="Bildschirm­foto 2023-01-19 um 17 28 56" src="https://user-images.githubusercontent.com/26705027/213498618-8a33596e-1815-4b2f-8807-ccd9a1c2fe5e.png">

I gave access to the prop **unauthenticated_read_product_inventory** of course.

Any ideas?

**Comment by walton-alex** [comment]
@Mritunjay004 As in un-install then re-install the app in the Shopify apps area?

**Comment by mwrigley** [comment]
The issue for me was I had to have 'unauthenticated_read_product_inventory' included in my scopes. This is not in the documentation, but was showing as an error in the response.
