### ISSUE TITLE
Select shipping options

### ISSUE THREAD

**Issue by kneeki** [Shopify/js-buy-sdk#766]
Is it possible using this SDK to retrieve a list of shipping lines from a checkout object, and update it if necessary? [The documentation](https://shopify.github.io/js-buy-sdk/CheckoutResource.html) doesn't give any information on this.

**Comment by StefanSlehta** [comment]
Hi! You can [expand the SDK](https://github.com/Shopify/js-buy-sdk#expanding-the-sdk) to fetch the additional fields you need. 
We don't fetch entire objects to reduce the performance and bandwidth impact, since most users don't need all the fields most of the time. 
Remember, js-buy uses the [storefront API](https://shopify.dev/docs/storefront-api/getting-started).

**Comment by jornwildenbeest** [comment]
@kneeki did you find a solution to your problem?
