### ISSUE TITLE
shopify-buy checkout.create() keeps throwing internal server error.

### ISSUE THREAD

**Issue by shashankraj0202** [Shopify/js-buy-sdk#810]
### Bug details 

**shopify-buy checkout.create() keeps throwing internal server error for one of our stores**

**To Reproduce**
```
const fetch = require("node-fetch");
const shopify = require('shopify-buy');

const client = shopify.buildClient({
    domain: ***,
    storefrontAccessToken: ***
}, fetch);

client.checkout.create().then((checkout) => {
                session.checkoutId = checkout.id;
                // some code here
            }).catch((error) => {
             // some code here
            });
```

### Response
```
[{"message":"Internal error. Looks like something went wrong on our end.\nRequest ID: 9c4c38a5-c579-4e9f-8ff4-4b6b2dc42f45 (include this in support requests).","extensions":{"code":"INTERNAL_SERVER_ERROR","requestId":"9c4c38a5-c579-4e9f-8ff4-4b6b2dc42f45"}}]
```

Request ID - 9c4c38a5-c579-4e9f-8ff4-4b6b2dc42f45

**Comment by tjennt** [comment]
I also had a similar situation!

**Comment by shashankraj0202** [comment]
@tessalt Were you able to resolve this?

**Comment by scottbaggett** [comment]
I am running into this same issue: Request id `c6a8dcc9-3e14-4d25-a4ab-a847e59d5a53`.  Has anyone solved this? I am not sure how to proceed.

**Comment by francispelland** [comment]
Just to note, if your shop is on a dormant plan you are likely going to get this error. We'll improve the error messaging though so that this can be more clear.

**Comment by Johnkinging** [comment]
This looks to be likely due to changes we needed to make restricting the storefront API checkout queries and mutation when a store is on the dormant plan. It was leading to plan abuse and order creation when those were not intended to be possible. Unfortunately it also restricts anyone trying to abide the full spirit of the "Pause and Build" trying to leverage our APIs for when the shop is back in full use. 

The implementation has been changed now so that the queries should return a more GraphQL friendly error rather than a 5XX.

If this cleaned up the Internal Server Errors, we can likely close this issue.
